export enum EmailTypeEnum {
  VERIFY_EMAIL = "VERIFY_EMAIL",
  RESET_PASSWORD = "RESET_PASSWORD",
  VERIFY_EMAIL_CHANGE = "VERIFY_EMAIL_CHANGE",
  VERIFY_USERNAME_CHANGE = "VERIFY_USERNAME_CHANGE",
  VERIFY_TEL_CHANGE = "VERIFY_TEL_CHANGE",
  VERIFY_PASSWORD_CHANGE = "VERIFY_PASSWORD_CHANGE"
}
